#!/bin/bash

# Définition des constantes
TMP=./tmp
FILE_LIST=$TMP/fileList
ARCHIVE_FOLDER=$TMP/archives

# Obtenir le type d'un fichier
getFileType()
{
    getFileType_fileType=`file $1 | cut -d ':' -f 2`
    echo $getFileType_fileType
}

# Obtenir la taille d'un fichier
getFileSize()
{
    getFileSize_fileSize=`wc -c $1 | cut -d ' ' -f 1`
    echo $getFileSize_fileSize
}

# Renvoie le nom d'un fichier sans le chemin de son dossier
getFileName()
{
    getFileName_path=$1
    basename $getFileName_path
}

# Crée un dossier et les dossiers parents si besoin
createFolder()
{
    createFolder_folder=$1
    if [ ! -d $createFolder_folder ]
        then
            mkdir -p $createFolder_folder
    fi
}

# liste dans ./temp/fileList.txt tous les fichiers d'un répertoire et ses sous répertoires
makeFileList()
{
    makeFileList_folder=$1
    `find $makeFileList_folder -type f > $FILE_LIST`
}

# Extrait une archive dans un dossier
extract()
{
    extract_archive=$1
    extract_destination=$2
    extract_fileName=`getFileName $extract_archive`
    echo "Nom du fichier : "$extract_fileName
    createFolder $extract_destination/$extract_archive
    cp $extract_archive $extract_destination/$extract_archive
    echo $extract_destination/$extract_archive/$extract_fileName
    tar -x $extract_destination/$extract_archive -f $extract_fileName
}


# Début du programme


# Définition du dossier de recherche
case $# in
    # Aucun parametre pour le script : on utilise ./ comme dossier de recherche
    0) 
        echo "Aucun dossier de recherche défini en parametre,"
        folder=./
    ;;
    # Un parametre : si c'est un dossier, on vérifie si il existe et on l'utilise comme dossier de recherche
    1) 
        folder=$1
        # On vérifie si le dossier existe. Si il n'existe pas, on sort du ptogramme
        if [ ! -d "$folder" ]
            then
                echo "Le dossier $folder n'existe pas"
                exit
        fi
    ;;
    # Plusieurs paramètres
    *) 
        echo "Les paramètres donnés sont invalides, sortie du programme"
        exit
    ;;
esac
echo "Recherche de fichiers à partir de $folder"

# Creation des dossiers tmp et archives
#mkdir $TMP
#mkdir $ARCHIVE_FOLDER
createFolder $TMP
createFolder $ARCHIVE_FOLDER

makeFileList $folder

extract ./repTest/rep2/archive2.tar.gz $ARCHIVE_FOLDER

# Suppression du dossier tmp
#rm -r ./tmp
